FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:ondrej/php
RUN apt-get update
RUN apt-get install -y apache2 apache2-utils php5.6 php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml php5.6-intl php5.6-intl php5.6-mbstring php5.6-cli php5.6-gd php5.6-curl php5.6-sqlite3 libapache2-mod-php5.6
RUN rm -rf /var/www/html/*
COPY simabes/ /var/www/html/
RUN apt clean
WORKDIR /var/www/html
CMD ["apache2ctl","-D","FOREGROUND"]
EXPOSE 80
