FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y apache2 apache2-utils php libapache2-mod-php git
RUN rm -rf /var/www/html/*
RUN git clone https://github.com/rivawahyuda/kalkulator.git /var/www/html
RUN apt clean
WORKDIR /var/www/html
CMD ["apache2ctl","-D","FOREGROUND"]
EXPOSE 80
